title: Anshaoyan.blog
description: 安绍岩的Github博客
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

<<<<<<< HEAD
gems:
  - jekyll-mentions
=======
title: BeiYuu.com
url: http://beiyuu.com
feed: /atom.xml
author_info: <a href="http://beiyuu.com/">BeiYuu</a>

theme: jekyll-theme-cayman
>>>>>>> 5010864849943b49e0b346839c3a8d4b55b842fd
